// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrR-HyQKFMTpqkNMbbbyYFnqSXqcrRBRs',
    appId: '1:465765073368:web:a22b5047e704e4dc8872ad',
    messagingSenderId: '465765073368',
    projectId: 'flutterappdemo-e50b0',
    authDomain: 'flutterappdemo-e50b0.firebaseapp.com',
    storageBucket: 'flutterappdemo-e50b0.appspot.com',
    measurementId: 'G-D6VMY6RS3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMeVrFm90Ra7jzptoTr1MxmUbSkcYSi-U',
    appId: '1:465765073368:android:23dc914e06a3a4fc8872ad',
    messagingSenderId: '465765073368',
    projectId: 'flutterappdemo-e50b0',
    storageBucket: 'flutterappdemo-e50b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBozkcWj_sNJEr6KYwU3NPatrPkNRHAdQA',
    appId: '1:465765073368:ios:ba272443ec9d21068872ad',
    messagingSenderId: '465765073368',
    projectId: 'flutterappdemo-e50b0',
    storageBucket: 'flutterappdemo-e50b0.appspot.com',
    iosClientId: '465765073368-l3h67emt8n84aaenvo71jgh9g85h8cuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.postApiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBozkcWj_sNJEr6KYwU3NPatrPkNRHAdQA',
    appId: '1:465765073368:ios:ba272443ec9d21068872ad',
    messagingSenderId: '465765073368',
    projectId: 'flutterappdemo-e50b0',
    storageBucket: 'flutterappdemo-e50b0.appspot.com',
    iosClientId: '465765073368-l3h67emt8n84aaenvo71jgh9g85h8cuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.postApiApp',
  );
}
