// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZLmlfY9gJ_Q2YcTXvBWiz4MU_hH9wOg',
    appId: '1:560903509465:web:64cba436162f1c21e4f5c8',
    messagingSenderId: '560903509465',
    projectId: 'horoscope-app-73a0d',
    authDomain: 'horoscope-app-73a0d.firebaseapp.com',
    storageBucket: 'horoscope-app-73a0d.appspot.com',
    measurementId: 'G-X9R9HW38E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMQKPEFd06kqvPbiS7gTC2XcmrJ2iVOZM',
    appId: '1:560903509465:android:4e7210c0a220226be4f5c8',
    messagingSenderId: '560903509465',
    projectId: 'horoscope-app-73a0d',
    storageBucket: 'horoscope-app-73a0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhah5XzTF7Jd8R5oY7p-teF69wG0gjBxQ',
    appId: '1:560903509465:ios:b42b09b382d3b677e4f5c8',
    messagingSenderId: '560903509465',
    projectId: 'horoscope-app-73a0d',
    storageBucket: 'horoscope-app-73a0d.appspot.com',
    iosClientId: '560903509465-923rbb3vicolv9edm4hgsf1cu61ngo4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.horoscopeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhah5XzTF7Jd8R5oY7p-teF69wG0gjBxQ',
    appId: '1:560903509465:ios:b42b09b382d3b677e4f5c8',
    messagingSenderId: '560903509465',
    projectId: 'horoscope-app-73a0d',
    storageBucket: 'horoscope-app-73a0d.appspot.com',
    iosClientId: '560903509465-923rbb3vicolv9edm4hgsf1cu61ngo4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.horoscopeApp',
  );
}
